### ISSUE TITLE
Add-on seems to alter the Changed field of tickets every 5 minutes

### ISSUE THREAD

**Issue by gjsjohnmurray** [znuny/Znuny4OTRS-EscalationSuspend#9] opened 2015-05-18 10:06 UTC
I think the processing done by this add-on's cron entry is causing the Changed field of many of my tickets to be updated every 5 minutes. This means that displaying the Changed column on my dashboard lists is useless, because I can no longer tell when a "real" change was made to a ticket.

**Comment by thorsteneckel** [comment] 2015-05-18 13:29
Hi @gjsjohnmurray and thanks for your feedback. We discussed your point internally and agreed with you. I have already worked out a fix for this behavior which I will be able to test this week. So stay tuned :) 

Best Regards,
 Thorsten

**Comment by thorsteneckel** [comment] 2015-05-22 10:34
Hi @gjsjohnmurray ! I fixed the issue in the master branch which provides the code for OTRS 4. The issue is fixed in version 2.1.1 of Znuny4OTRS-EscalationSuspend.

I fixed some other issues on the way which are shown in the commit history. It seems to me that the script might have never worked in the OTRS 4 version of the package. Can you verify this?

Best regards and thanks for the hint.

**Comment by gjsjohnmurray** [comment] 2015-05-22 11:15
I have upgraded to 2.1.1 and this has fixed the problem of Changed field updating every 5 minutes. 

How would you like me to verify that the script is working now?

Thanks,

John

**Comment by thorsteneckel** [comment] 2015-05-22 12:11
Thanks for your fast reply John. Glad to hear that it fixed the bug. You can verify it by running the script via:

```
cd $OTRS
perl bin/znuny.RebuildEscalationIndexOnline.pl
```

**Closed** 2015-05-22 12:42 UTC
